name: spellcheck

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: workflow_call

jobs:
  spelling:
    runs-on: ubuntu-latest
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
    env:
      sharedConfigRepo: spell-check-lint-action
      configPath: .github/actions/spelling
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    steps:
      - name: checkout from default branch
        uses: actions/checkout@v3
      - name: Clone shared config
        run: git clone https://github.com/Shypyard/$sharedConfigRepo.git
      - name: Merge configs
        run: |
          mkdir ./tmp
          if [ ! -d "$configPath" ]; then mkdir ./$configPath; fi
          mv ./$configPath/* ./tmp/
          cp ./$sharedConfigRepo/$configPath/* ./$configPath/
          mv ./tmp/* ./$configPath/
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@main
        with:
          only_check_changed_files: 1
          quit_without_error: 1
          check_file_names: 1
          post_comment: 0
          use_magic_file: 1
          check_commit_messages: commits title
          dictionary_source_prefixes: >
            {
              "shypyard": "https://raw.githubusercontent.com/Shypyard/spell-check-lint-action/main/",
              "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220816/dictionaries/"
            }
          extra_dictionaries: shypyard:dictionary.txt
            cspell:aws/aws.txt
            cspell:companies/src/companies.txt
            cspell:css/css.txt
            cspell:filetypes/filetypes.txt
            cspell:fonts/fonts.txt
            cspell:fullstack/fullstack.txt
            cspell:html/html.txt
            cspell:node/node.txt
            cspell:npm/npm.txt
            cspell:software-terms/src/software-terms.txt
            cspell:software-terms/src/software-tools.txt
            cspell:typescript/typescript.txt

  comment-pr:
    name: Report (PR)
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      pull-requests: write
    if: (success() || failure()) && needs.spelling.outputs.followup && contains(github.event_name, 'pull_request')
    steps:
      - name: comment
        uses: check-spelling/check-spelling@main
        with:
          task: ${{ needs.spelling.outputs.followup }}
